package: nanshe
platform:
  - linux-64
  #- osx-64
  #- win-64
engine:
  - python=2.7
script:
  - conda build openblas fftw boost numpy scipy bottleneck pyfftw vigra rank_filter spams nanshe
build_targets:
  files: conda
  channels: main
