package:
  name: monty
  version: "0.6.4"

source:
  fn: monty-0.6.4.tar.gz
  url: https://pypi.python.org/packages/source/m/monty/monty-0.6.4.tar.gz
  md5: cc6f011b73038ab7c2fe9199ae0cd34f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - monty = monty:main
    #
    # Would create an entry point called monty that calls monty.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - pyyaml
    - setuptools
    - six

  run:
    - python
    - pyyaml
    - six

test:
  # Python imports
  imports:
    - monty
    - monty.os

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/materialsvirtuallab/monty
  license: MIT License
  summary: 'Monty is the missing complement to Python.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
