package:
  name: openblas
  version: 0.2.14

source:
  fn: openblas-0.2.14.tgz
  url: http://github.com/xianyi/OpenBLAS/tarball/v0.2.14
#  patches:
#    - affinity.patch

build:
  number: 669

requirements:
  build:
    - gcc

  run:
    - gcc

about:
  home: http://xianyi.github.io/OpenBLAS/
  license: BSD
