package:
  name: scipy
  version: 0.14.0

source:
  url: https://pypi.python.org/packages/source/s/scipy/scipy-0.14.0.tar.gz
  fn: scipy-0.14.0.tar.gz

requirements:
  build:
    - python
    - openblas
    - numpy
    #- blas
    #- lapack
    #- atlas

  run:
    - python
    - openblas
    - numpy

build:
  number: 1

about:
  home: https://www.scipy.org
  license: PSF
