package:
  name: fireworks
  version: "1.1.1"

source:
  fn: FireWorks-1.1.1.tar.gz
  url: https://pypi.python.org/packages/source/F/FireWorks/FireWorks-1.1.1.tar.gz
  md5: 7e792703a5bb0abd757544916e5fcd1a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - fireworks = fireworks:main
    #
    # Would create an entry point called fireworks that calls fireworks.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyyaml >=3.1.0
    - pymongo >=3.0
    - jinja2 >=2.7.3
    - six >=1.5.2
    - monty >=0.5.6
    - python-dateutil >=2.2

  run:
    - python
    - pyyaml >=3.1.0
    - pymongo >=3.0
    - jinja2 >=2.7.3
    - six >=1.5.2
    - monty >=0.5.6
    - python-dateutil >=2.2

test:
  # Python imports
  imports:
    - fireworks
    - fireworks.core
    - fireworks.core.tests
    - fireworks.features
    - fireworks.flask_site
    - fireworks.queue
    - fireworks.scripts
    - fireworks.tests
    - fireworks.user_objects
    - fireworks.user_objects.dupefinders
    - fireworks.user_objects.firetasks
    - fireworks.user_objects.firetasks.tests
    - fireworks.user_objects.queue_adapters
    - fireworks.user_objects.queue_adapters.tests
    - fireworks.utilities
    - fireworks.utilities.tests
    - fw_tutorials
    - fw_tutorials.dynamic_wf
    - fw_tutorials.firetask
    - fw_tutorials.python

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/materialsproject/fireworks
  license: modified BSD
  summary: 'FireWorks workflow software'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
