package:
  name: numpy
  version: 1.10.4

source:
  url: https://github.com/numpy/numpy/archive/v1.10.4.tar.gz
  fn: numpy-1.10.4.tar.gz

requirements:
  build:
    - python
    - openblas 

  run:
    - python
    - openblas

build:
  number: 100

  features:
    - openblas

about:
  home: https://www.numpy.org
  license: PSF
